name: CI Pull Request

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".idea/**"
jobs:
    checks:
        uses: ./.github/workflows/run-checks.yml
